[workspace]
members = [
    "crates/stateless-validator-catalog",
    "crates/stateless-validator-common",
    "crates/stateless-validator-downloader",
    "crates/stateless-validator-test",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.93"
version = "0.16.0"

[workspace.lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "deny", priority = -1 }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_must_use = "deny"

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
result_large_err = "allow"

[workspace.dependencies]
anyhow = { version = "1.0", default-features = false }
clap = { version = "4.6.0", features = ["derive"] }
const-hex = { version = "1.19", default-features = false }
serde = { version = "1.0", default-features = false }
sha2 = { version = "0.10.9", default-features = false }
strum = { version = "0.28.0", default-features = false }
thiserror = { version = "2.0", default-features = false }

# test/util
dashmap = "6.2"
flate2 = "1.1.5"
rayon = "1.11.0"
reqwest = "0.12"
semver = "1.0.28"
serde_json = "1.0"
tar = "0.4.44"
tempfile = "3.6.0"
tokio = "1"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
walkdir = "2.5.0"
zstd = "0.13.3"
paste = "1.0"

# ssz
libssz = { version = "0.3.0", default-features = false, features = ["alloc"] }
libssz-derive = "0.3.0"
libssz-merkle = { version = "0.3.0", default-features = false, features = [
    "alloc",
    "sha2-backend",
] }
libssz-types = { version = "0.3.0", default-features = false, features = ["alloc"] }

# fixture JSON byte strings
alloy-primitives = { version = "1.6.1", default-features = false }

# ere
ere-catalog = { git = "https://github.com/eth-act/ere", tag = "v0.17.0" }
ere-dockerized = { git = "https://github.com/eth-act/ere", tag = "v0.17.0" }

# local
stateless-validator-catalog = { path = "crates/stateless-validator-catalog" }
stateless-validator-common = { path = "crates/stateless-validator-common", default-features = false }
