[package]
name = "stateless-validator-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
const-hex = { workspace = true, features = ["alloc"] }
sha2.workspace = true
thiserror.workspace = true

# ssz
libssz.workspace = true
libssz-derive.workspace = true
libssz-merkle = { workspace = true, features = ["sha2-backend"] }
libssz-types.workspace = true

# alloy
alloy-consensus = { workspace = true, optional = true }
alloy-eips = { workspace = true, optional = true }
alloy-genesis = { workspace = true, optional = true }
alloy-primitives = { workspace = true, optional = true }

# reth
reth-chainspec = { workspace = true, optional = true }
reth-ethereum-primitives = { workspace = true, optional = true }
reth-evm-ethereum = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, optional = true }
reth-stateless = { workspace = true, optional = true }
reth-tries = { workspace = true, optional = true }

[features]
# guest
default = ["std"]
std = []

# host
host = ["std"]

# legacy
legacy = [
    "host",
    "dep:anyhow",
    "dep:alloy-consensus",
    "dep:alloy-eips",
    "dep:alloy-genesis",
    "dep:alloy-primitives",
    "dep:reth-chainspec",
    "dep:reth-ethereum-primitives",
    "dep:reth-evm-ethereum",
    "dep:reth-primitives-traits",
    "dep:reth-stateless",
    "dep:reth-tries",
]
