[package]
name = "stateless-validator-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
const-hex = { workspace = true, features = ["alloc"] }
paste.workspace = true
sha2.workspace = true
thiserror.workspace = true

# ssz
libssz.workspace = true
libssz-derive.workspace = true
libssz-merkle = { workspace = true, features = ["sha2-backend"] }
libssz-types.workspace = true

[dev-dependencies]
hex-literal.workspace = true

[features]
# guest
default = ["std"]
std = []

# host
host = ["std"]
