//! VK regeneration tests for republished guest programs.
//!
//! Run with env `ERE_IMAGE_REGISTRY=ghcr.io/eth-act/ere` to use the pre-built
//! image as the executor.

use ere_dockerized::zkVMKind;
use stateless_validator_catalog::StatelessValidatorKind;
use stateless_validator_test::execution::zkvm::{download_elf, download_vk, init_zkvm};

/// Asserts the VK published can be regenerated by Ere given the published ELF.
fn test_vk_regeneration(stateless_validator_kind: StatelessValidatorKind, zkvm_kind: zkVMKind) {
    let published = download_vk(stateless_validator_kind, zkvm_kind);
    let elf = download_elf(stateless_validator_kind, zkvm_kind);
    let regenerated = init_zkvm(zkvm_kind, elf).program_vk().to_vec();
    assert_eq!(
        const_hex::encode_prefixed(&regenerated),
        const_hex::encode_prefixed(&published),
    );
}

macro_rules! declare_test {
    ($stateless_validator:ident, $zkvm_kind:ident) => {
        paste::paste! {
            #[test]
            fn [<test_vk_regeneration_ $stateless_validator:lower _ $zkvm_kind:lower>]() {
                test_vk_regeneration(
                    StatelessValidatorKind::$stateless_validator,
                    zkVMKind::$zkvm_kind,
                );
            }
        }
    };
}

// Zesu

declare_test!(Zesu, Zisk);
