//! Fixture loading and test runner for the stateless validator.

use std::{
    fs::{self, File},
    path::{Path, PathBuf},
};

use serde::Deserialize;
use tar::Archive;
use walkdir::WalkDir;

/// A fixture normalized to canonical schema-prefixed SSZ input bytes.
#[derive(Debug, Clone)]
pub struct StatelessValidatorFixture {
    /// Human-readable fixture identifier.
    pub name: String,
    /// Canonical schema-prefixed SSZ input bytes consumed by the guests.
    pub input_bytes: Vec<u8>,
    /// Expected validation outcome.
    pub success: bool,
    /// Expected serialized guest output, when the fixture carries one.
    pub expected_output_bytes: Option<Vec<u8>>,
}

/// Reads every stateless validator fixture.
pub fn get_fixtures() -> Vec<StatelessValidatorFixture> {
    let mut fixtures = untar_fixtures()
        .into_iter()
        .flat_map(load_fixtures_from_dir)
        .collect::<Vec<_>>();
    fixtures.sort_by(|a, b| a.name.cmp(&b.name));
    fixtures
}

/// Extracts every `.tar.zst` archive under the fixtures dir into a sibling
/// directory named after the archive.
fn untar_fixtures() -> Vec<PathBuf> {
    let fixtures_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures");
    let archives = WalkDir::new(fixtures_dir)
        .max_depth(2)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry.file_type().is_file()
                && entry
                    .file_name()
                    .to_str()
                    .is_some_and(|name| name.ends_with(".tar.zst"))
        })
        .map(walkdir::DirEntry::into_path);

    let mut extracted = Vec::new();
    for archive in archives {
        let stem = archive
            .file_name()
            .and_then(|name| name.to_str())
            .map(|name| name.trim_end_matches(".tar.zst"))
            .unwrap();
        let target = archive.parent().unwrap().join(stem);
        fs::create_dir_all(&target).unwrap();
        let decoder = zstd::stream::read::Decoder::new(File::open(&archive).unwrap()).unwrap();
        Archive::new(decoder).unpack(&target).unwrap();
        extracted.push(target);
    }

    extracted
}

/// Loads every fixture found under a directory or a single fixture file.
fn load_fixtures_from_dir(path: impl AsRef<Path>) -> Vec<StatelessValidatorFixture> {
    WalkDir::new(path)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry.file_type().is_file()
                && entry
                    .file_name()
                    .to_str()
                    .is_some_and(|name| name.ends_with(".json.zst"))
        })
        .map(|entry| load_fixture(entry.path()))
        .collect()
}

/// Loads a stateless input artifact generated by `witness-generator-spec-cli`
/// compressed by zstd.
fn load_fixture(path: &Path) -> StatelessValidatorFixture {
    #[derive(Debug, Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct StatelessInputArtifact {
        stateless_input_bytes: alloy_primitives::Bytes,
        stateless_output_bytes: alloy_primitives::Bytes,
        block_number: u64,
        network: String,
    }

    let bytes = zstd::stream::decode_all(fs::read(path).unwrap().as_slice()).unwrap();
    let artifact: StatelessInputArtifact = serde_json::from_slice(&bytes).unwrap();

    StatelessValidatorFixture {
        name: format!("{}-rpc-{}", artifact.network, artifact.block_number),
        input_bytes: artifact.stateless_input_bytes.to_vec(),
        success: true,
        expected_output_bytes: Some(artifact.stateless_output_bytes.to_vec()),
    }
}
