//! Fixture loading and test runner for the stateless validator.

use std::{
    fs::{self, File},
    path::{Path, PathBuf},
};

use serde::Deserialize;
use tar::Archive;
use tracing::info;
use walkdir::WalkDir;

/// Base URL of the GitHub release hosting the per-fork fixture archives.
const FIXTURES_BASE_URL: &str =
    "https://github.com/han0110/ere-guests/releases/download/tests-zkevm@v0.4.1";

/// Ethereum fork a fixture set targets.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Fork {
    /// Fusaka (mainnet) fixtures.
    Fusaka,
    /// Glamsterdam devnet-5 fixtures.
    Glamsterdam,
}

impl Fork {
    /// Subdirectory under `fixtures/` holding this fork's data, which is also
    /// the stem of its release archive (`<subdir>.tar.zst`).
    pub fn subdir(self) -> &'static str {
        match self {
            Fork::Fusaka => "fusaka",
            Fork::Glamsterdam => "glamsterdam-devnet-5",
        }
    }
}

/// A fixture normalized to canonical schema-prefixed SSZ input bytes.
#[derive(Debug, Clone)]
pub struct StatelessValidatorFixture {
    /// Human-readable fixture identifier.
    pub name: String,
    /// Canonical schema-prefixed SSZ input bytes consumed by the guests.
    pub input_bytes: Vec<u8>,
    /// Expected validation outcome.
    pub success: bool,
    /// Expected serialized guest output, when the fixture carries one.
    pub expected_output_bytes: Option<Vec<u8>>,
}

/// Reads every stateless validator fixture for `fork`, downloading and
/// extracting the fork's archive on demand when it is not already present.
pub fn get_fixtures(fork: Fork) -> Vec<StatelessValidatorFixture> {
    let mut fixtures = load_fixtures_from_dir(ensure_fixtures(fork));
    fixtures.sort_by(|a, b| a.name.cmp(&b.name));
    fixtures
}

/// Ensures the extracted fixture directory for `fork` exists, downloading and
/// unpacking the release archive when it is missing. Returns the directory.
fn ensure_fixtures(fork: Fork) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join(fork.subdir());
    if !dir.exists() {
        download_fixtures(fork, &dir);
    }
    dir
}

/// Downloads the fork's release archive and unpacks it into `dir`.
fn download_fixtures(fork: Fork, dir: &Path) {
    let url = format!("{FIXTURES_BASE_URL}/{}.tar.zst", fork.subdir());

    info!("Downloading fixture archive {url}");

    let resp = reqwest::blocking::get(url.as_str()).unwrap();
    let bytes = resp.error_for_status().unwrap().bytes().unwrap();

    let tempdir = tempfile::tempdir_in(dir.parent().unwrap()).unwrap();
    let archive = tempdir.path().join(format!("{}.tar.zst", fork.subdir()));
    fs::write(&archive, &bytes).unwrap();

    let decoder = zstd::stream::read::Decoder::new(File::open(&archive).unwrap()).unwrap();
    Archive::new(decoder).unpack(tempdir.path()).unwrap();

    fs::rename(tempdir.path().join(fork.subdir()), dir).unwrap();
}

/// Loads every fixture found under a directory or a single fixture file.
fn load_fixtures_from_dir(path: impl AsRef<Path>) -> Vec<StatelessValidatorFixture> {
    WalkDir::new(path)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry.file_type().is_file()
                && entry
                    .file_name()
                    .to_str()
                    .is_some_and(|name| name.ends_with(".json.zst"))
        })
        .map(|entry| load_fixture(entry.path()))
        .collect()
}

/// Loads a stateless input artifact generated by `witness-generator-spec-cli`
/// compressed by zstd.
fn load_fixture(path: &Path) -> StatelessValidatorFixture {
    #[derive(Debug, Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct StatelessInputArtifact {
        stateless_input_bytes: alloy_primitives::Bytes,
        stateless_output_bytes: alloy_primitives::Bytes,
        block_number: u64,
        network: String,
    }

    let bytes = zstd::stream::decode_all(fs::read(path).unwrap().as_slice()).unwrap();
    let artifact: StatelessInputArtifact = serde_json::from_slice(&bytes).unwrap();

    StatelessValidatorFixture {
        name: format!("{}-rpc-{}", artifact.network, artifact.block_number),
        input_bytes: artifact.stateless_input_bytes.to_vec(),
        success: true,
        expected_output_bytes: Some(artifact.stateless_output_bytes.to_vec()),
    }
}
