[package]
name = "stateless-validator-ethrex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
hex-literal.workspace = true

# ethrex
ethrex-common.workspace = true
ethrex-crypto.workspace = true
ethrex-guest-program = { workspace = true, features = ["eip-8025"] }

# zkvm-standard
zkvm-interface = { workspace = true, optional = true }

# ere
ere-platform-core.workspace = true

# local
recursive-execution-proof.workspace = true
stateless-validator-common.workspace = true

[dev-dependencies]
paste.workspace = true
ere-dockerized.workspace = true
stateless-validator-test.workspace = true

[[test]]
name = "host_execution"
required-features = ["host"]

[features]
# guest
default = ["std"]
std = ["recursive-execution-proof/std", "stateless-validator-common/std"]
openvm = ["zkvm-interface"]
sp1 = ["zkvm-interface"]
zisk = ["zkvm-interface"]
zkvm-interface = ["dep:zkvm-interface"]

# host
# NOTE: Need `ethrex-crypto/blst` and `ethrex-crypto/kzg-rs` for execution on host.
host = ["std", "ethrex-crypto/blst", "ethrex-crypto/kzg-rs", "ethrex-crypto/secp256k1", "stateless-validator-common/host"]
