[package]
name = "stateless-validator-ethrex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
hex-literal.workspace = true

# ethrex
ethrex-common.workspace = true
ethrex-crypto.workspace = true
ethrex-guest-program = { workspace = true, features = ["eip-8025"] }

# zkvm-standard
zkvm-interface = { workspace = true, optional = true }

# ere
ere-platform-core.workspace = true

# local
stateless-validator-common.workspace = true

[dev-dependencies]
paste.workspace = true
ere-dockerized.workspace = true
stateless-validator-test.workspace = true

[build-dependencies]
ere-util-build.workspace = true

[features]
# guest
default = ["std"]
std = ["stateless-validator-common/std"]
sp1 = ["ethrex-guest-program/sp1", "ethrex-guest-program/secp256k1"]
zisk = ["zkvm-interface"]
zkvm-interface = ["dep:zkvm-interface"]

# host
# NOTE: Need `ethrex-crypto/blst` and `ethrex-crypto/kzg-rs` for execution on host.
host = ["std", "ethrex-crypto/blst", "ethrex-crypto/kzg-rs", "ethrex-crypto/secp256k1", "stateless-validator-common/host"]
