[package]
name = "stateless-validator-ethrex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
hex-literal.workspace = true

# ethrex
ethrex-common.workspace = true
ethrex-crypto.workspace = true
ethrex-guest-program = { workspace = true, features = ["eip-8025"] }

# openvm

openvm-ecc-guest = { workspace = true, optional = true }
openvm-sha2 = { workspace = true, optional = true }
openvm-pairing = { workspace = true, features = ["bn254", "bls12_381"], optional = true }
openvm-k256 = { workspace = true, optional = true }
openvm-p256 = { workspace = true, optional = true }
openvm-keccak256 = { workspace = true, optional = true }
openvm-curve-utils = { workspace = true, optional = true }
openvm-kzg = { workspace = true, optional = true }
bls12_381 = { workspace = true, features = ["experimental"], optional = true }

# zkvm-standard
zkvm-interface = { workspace = true, optional = true }

# ere
ere-platform-core.workspace = true

# local
stateless-validator-common.workspace = true

[dev-dependencies]
paste.workspace = true
ere-dockerized.workspace = true
stateless-validator-test.workspace = true

[build-dependencies]
ere-util-build.workspace = true

[features]
# guest
default = ["std"]
std = ["stateless-validator-common/std"]
openvm = [
    "dep:openvm-ecc-guest",
    "dep:openvm-sha2",
    "dep:openvm-pairing",
    "dep:openvm-k256",
    "dep:openvm-p256",
    "dep:openvm-keccak256",
    "dep:openvm-curve-utils",
    "dep:openvm-kzg",
    "dep:bls12_381",
]
sp1 = ["zkvm-interface"]
zisk = ["zkvm-interface"]
zkvm-interface = ["dep:zkvm-interface"]

# host
# NOTE: Need `ethrex-crypto/blst` and `ethrex-crypto/kzg-rs` for execution on host.
host = ["std", "ethrex-crypto/blst", "ethrex-crypto/kzg-rs", "ethrex-crypto/secp256k1", "stateless-validator-common/host"]
