[package]
name = "stateless-validator-debug"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# alloy
alloy-eips.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }

# reth
reth-stateless.workspace = true

# ere
ere-platform-core.workspace = true

# local
stateless-validator-common = { workspace = true, features = ["host"] }
stateless-validator-ethrex = { workspace = true, default-features = true, features = [
    "host",
] }
stateless-validator-reth = { workspace = true, default-features = true, features = [
    "host",
] }
