name: Test and clippy lib crates

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check fmt
        run: .github/scripts/check-fmt.sh

  test:
    name: Test and clippy crate ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - guest
          - block-encoding-length
          - stateless-validator-ethrex
          - stateless-validator-reth
        exclude:
          # ethereum_ssz is not no_std compatible
          - crate: block-encoding-length
            skip_compile_to_riscv32imac: true
          # ethrex is not no_std compatible
          - crate: stateless-validator-ethrex
            skip_compile_to_riscv32imac: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check clippy
        run: cargo clippy --all-targets --package ${{ matrix.crate }} -- -D warnings

      - name: Test on documentation
        run: cargo test --doc --package ${{ matrix.crate }}

      - name: Test
        run: cargo test --all-targets --package ${{ matrix.crate }}

      - name: Compile to target riscv32imac-unknown-none-elf
        if: matrix.skip_compile_to_riscv32imac != true
        run: cargo build --package ${{ matrix.crate }} --no-default-features --target riscv32imac-unknown-none-elf
