name: Integration test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test execution of ${{ matrix.guest }} on ${{ matrix.zkvm }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        guest:
          - block-encoding-length
          - empty
          - panic
          - stateless-validator-ethrex
          - stateless-validator-reth
        zkvm:
          - airbender
          - openvm
          - pico
          - risc0
          - sp1
          - zisk
        exclude:
          - guest: stateless-validator-ethrex
            zkvm: airbender
          - guest: stateless-validator-ethrex
            zkvm: openvm
          - guest: stateless-validator-ethrex
            zkvm: pico
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        if: matrix.zkvm == 'zisk'
        run: bash .github/scripts/free-up-disk-space.sh

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            bin/${{ matrix.guest }}/${{ matrix.zkvm }} -> target

      - name: Test
        env:
          ERE_IMAGE_REGISTRY: ghcr.io/eth-act/ere
        run: |
          cargo test --test ${{ matrix.guest }} -- ${{ matrix.zkvm }}

          sudo chown -R $(id -u):$(id -g) bin/${{ matrix.guest }}/${{ matrix.zkvm }}/target || true
