name: Integration test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test execution of ${{ matrix.guest }} on ${{ matrix.zkvm }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        guest:
          - block-encoding-length
          - empty
          - panic
          - stateless-validator-ethrex
          - stateless-validator-reth
        zkvm:
          - airbender
          - openvm
          - pico
          - risc0
          - sp1
          - zisk
        exclude:
          - guest: stateless-validator-ethrex
            zkvm: airbender
          - guest: stateless-validator-ethrex
            zkvm: openvm
          - guest: stateless-validator-ethrex
            zkvm: pico
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            bin/${{ matrix.guest }}/${{ matrix.zkvm }} -> target

      - name: Get Ere tag
        id: get_ere_tag
        run: |
          ERE_TAG=$(cargo tree -p ere-platform-trait | head -n 1 | sed -E 's/ere-platform-trait v([0-9.]+) \(.*#([a-f0-9]{7}).*/\1-\2/')
          echo "ere_tag=${ERE_TAG}" >> $GITHUB_OUTPUT
          echo "Ere tag: ${ERE_TAG}"

      - name: Pull compiler image
        run: |
          docker pull ghcr.io/eth-act/ere/ere-compiler-${{ matrix.zkvm }}:${{ steps.get_ere_tag.outputs.ere_tag }}

      - name: Test
        env:
          ERE_IMAGE_REGISTRY: ghcr.io/eth-act/ere
        run: |
          cargo test --test ${{ matrix.guest }} -- ${{ matrix.zkvm }}

          sudo chown -R $(id -u):$(id -g) bin/${{ matrix.guest }}/${{ matrix.zkvm }}/target || true
