name: Unit test and clippy

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check fmt
        run: .github/scripts/cargo-fmt-all.sh --check

  check-cargo-lock:
    name: Check Cargo.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check Cargo.lock is synced with Cargo.toml
        shell: bash
        run: .github/scripts/cargo-fetch-all.sh --locked

      - name: Check for unused [patch] entries
        shell: bash
        run: .github/scripts/check-unused-patch.sh

      - name: Check for duplicate packages
        shell: bash
        run: |
          .github/scripts/check-duplicate-pkg.sh \
            --include '^(alloy|ethrex|ere|reth|revm)' \
            --exclude '^alloy-trie$' # Crate `mpt` depends on an older `alloy-trie` but it's okay.

  test:
    name: Test and clippy workspace crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: riscv32imac-unknown-none-elf

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Test on documentation
        run: cargo test --doc --no-fail-fast

      - name: Test lib
        run: cargo test --lib --no-fail-fast

      # Include the package once the issue is resolved:
      # - `block-encoding-length` - `ethereum_ssz` is not no_std compatible
      # - `stateless-validator-ethrex` - ethrex is not no_std compatible
      - name: Compile to target riscv32imac-unknown-none-elf
        run: |
          cargo build \
            --workspace \
            --no-default-features \
            --target riscv32imac-unknown-none-elf \
            --exclude integration-tests \
            --exclude block-encoding-length \
            --exclude stateless-validator-ethrex
