name: Unit test and clippy

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check fmt
        run: .github/scripts/cargo-fmt-all.sh --check

  check-cargo-lock:
    name: Check Cargo.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check Cargo.lock is synced with Cargo.toml
        shell: bash
        run: .github/scripts/cargo-fetch-all.sh --locked

      - name: Check for unused [patch] entries
        shell: bash
        run: .github/scripts/check-unused-patch.sh

  test:
    name: Test and clippy workspace crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: riscv64imac-unknown-none-elf

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Test on documentation
        run: cargo test --doc --no-fail-fast

      - name: Test lib
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo test --lib --no-fail-fast

      - name: Compile common schemas for riscv64imac-unknown-none-elf
        run: |
          cargo build \
            --no-default-features \
            --target riscv64imac-unknown-none-elf \
            --package stateless-validator-common
