[package]
name = "stateless-validator-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
once_cell.workspace = true
thiserror.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, default-features = false, features = [
    "serde",
] }

# revm
revm.workspace = true

# reth
reth-chainspec.workspace = true
reth-payload-validator = { workspace = true, default-features = false }
reth-ethereum-primitives.workspace = true
reth-evm-ethereum.workspace = true
reth-primitives-traits.workspace = true
reth-stateless.workspace = true
reth-tries.workspace = true

# zkvm-standard
zkvm-interface = { workspace = true, optional = true }

# ere
ere-platform-core.workspace = true

# local
stateless-validator-common.workspace = true

[dev-dependencies]
ere-dockerized.workspace = true
stateless-validator-test.workspace = true

[build-dependencies]
ere-util-build.workspace = true

[features]
# guest
default = ["std"]
std = ["once_cell/std", "stateless-validator-common/std"]
openvm = []
zisk = ["zkvm-interface"]
zkvm-interface = ["alloy-consensus/crypto-backend", "dep:zkvm-interface"]

# host
host = ["std", "stateless-validator-common/host"]
